version: "3.0"
services:
  mongodb:
    image: mongo:4.0-xenial
    hostname: mongodb
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - ./server/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./server/mongodb/mongod.conf:/etc/mongod.conf:ro
